"""Add activity start date

Revision ID: 82cbe2b13c37
Revises: c352b316c914
Create Date: 2026-10-06 09:28:21.442862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82cbe2b13c37'
down_revision = 'c352b316c914'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Add start_date temporarily allowing NULL
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('start_date', sa.Date(), nullable=True)
        )

    # 2. Existing activities inherit their parent goal's start date
    op.execute("""
        UPDATE activities
        SET start_date = (
            SELECT goals.start_date
            FROM goals
            WHERE goals.id = activities.goal_id
        )
    """)

    # 3. After backfill, make start_date required
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column(
            'start_date',
            existing_type=sa.Date(),
            nullable=False
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
